### ISSUE TITLE
Agregar campo ethnicity (etnia) a user

### ISSUE THREAD

**Issue by cambioradical** [cambioradical/plataformaOnline#2]
export enum Ethnicity {
Caucásico = 1,
Afrodescendiente = 2,
Mestizo = 3,
Indígena = 4,
Raizal = 5,
ROM = 6,
Otra = 7
}

**Comment by Josnic** [comment]
Buenos días.

Se creó una entidad nueva en lugar de las enumeraciones. De igual forma se agregó los registros.

Saludos.
